/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const computed: (typeof import("vue"))["computed"]
  const defineEmits: (typeof import("vue"))["defineEmits"]
  const defineModel: (typeof import("vue"))["defineModel"]
  const defineProps: (typeof import("vue"))["defineProps"]
  const defineSlots: (typeof import("vue"))["defineSlots"]
  const onMounted: (typeof import("vue"))["onMounted"]
  const onUpdated: (typeof import("vue"))["onUpdated"]
  const reactive: (typeof import("vue"))["reactive"]
  const ref: (typeof import("vue"))["ref"]
  const watch: (typeof import("vue"))["watch"]
  const withDefaults: (typeof import("vue"))["withDefaults"]
}
